# Generated by Selenium IDE

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from home_page import HomePage

class TestDemo():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_demo(self):
    self.driver.get("https://tdd-detroid.onrender.com/")
    self.driver.set_window_size(970, 555)
    
    home_page = HomePage(self.driver)

    # Loop para que loading inicial da tela não trave o código:
    home_page.wait_load()
    # Ele fica buscando o elemento responsável pelo carregamento(.smooth) até que o mesmo não exista mais. Nesse momento, o loop se encerra.

    home_page.add_aluno('Nicolas')
    
    assert("INFO Added student id: 1, Name: Nicolas" 
           in home_page.get_log(None))
    
    home_page.add_curso('Matematica')

    assert("INFO Added student id: 1, Name: Nicolas" 
            in home_page.get_log(2))
    
    home_page.sub_to_course(1, 1)

    assert("INFO Added student id: 1, Name: Nicolas"
            in home_page.get_log(3))
    
    home_page.add_disciplina('mat', 1)

    assert("FAIL Necessários 3 cursos para se criar a primeira matéria"
      in home_page.get_log(1))
    
    home_page.add_curso('Portugues')

    home_page.add_curso('Geografia')

    home_page.add_disciplina('mat', 1)
    
    assert("INFO Added discipline id: 1, Name: mat, Course: 1"
      in home_page.get_log(1))
    
    home_page.add_disciplina('mat 2', 1)
    
    home_page.add_disciplina('mat 3', 1)

    home_page.sub_to_disciplina(1, 1)
    
    assert("WARN Aluno deve se inscrever em 3 materias no minimo"
            in home_page.get_log(1))
    
    home_page.sub_to_disciplina(1, 1)

    assert("FAIL Aluno 1 já está inscrito na matéria 1"
            in home_page.get_log(1))

    home_page.sub_to_disciplina(1, 2)

    home_page.sub_to_disciplina(1, 3)

    assert("INFO Student id 1, Name Nicolas subscribed to discipline id 3"
            in home_page.get_log(1))

    home_page.add_disciplina('mat 4', 1)

    assert("INFO Added discipline id: 4, Name: mat 4, Course: 1"
            in home_page.get_log(1))

    self.driver.close()

